language: node_js
node_js:
- 8
- 9
- 10
- 11
before_install:
- rm -rf node_modules
script:
- npm test && npm run e2e
after_success:
- npm run coverage
sudo: false
deploy:
  provider: npm
  email: npmjs.org@kimminich.de
  api_key:
    secure: Ct1lTpU5cht0OybpGB9+HfkWBBa1k6TPrnajp08cKYbeKUx1ybYdbkuM0z2F9XMeoyTHNcawYyqlHmNFcqSNwYpx7d54Mn7KkWWiUwpeekG+PPSzjoEMYkQt7Q1MQfwBV0kyzVFL+R1x9lg83BKDBGd/clwBAvZhMCDc/EiocTyVvkul9mhSBbsMLHyNeU1EVbyQdPDh2tsOQKPbpr4rCsH9xGes/VZQ6YWcJvyCwDryj4VlNsH4USJvuG992yy5RT0kg2gAcUm8gq3wkzlRPkJWT4RFmdxyzidWOPq6DPZfULNQ3z+gmZxeyNJJkAZHFYPIZC66xKxx8/3e3cuX+dS1E4LofwLpB3bydnFmOVaAWA0pdD/tlWFLPBK5GzA13BHTG2zJdaeSo1CxS98i2Yoj5JsQrnW0mDp/7AH47eAznaWTsukEKYCFjmu0fUMI5SWV4CXtWCzNxb9E8UqboM0j92aH3R3BIBVWytnRfBXyD5gACfLNM6V4SJVaXPG5apdj2jX4tiHruug6uUzSIxuVhtOH+PXrBC49ZNmM3gFclz6qcwcT7eUxsR4c38CNCByuzn/bA9IEvIpAK2/KqLodWdaivGmt/2PKBt9BhOSaWaep7+ZKkBMVE5yeuUI3w/ZDXavooYfw9CqsrmDfRC0H1L6zWaiyuhnyRjH0bIE=
  on:
    tags: true
    repo: bkimminich/juice-shop-ctf
    node: 10
notifications:
  slack:
    rooms:
      secure: CkJv/srViebermSM6E9dNFGDGaY5bwHhUqUfv02Mj2qUPOfpAILOoTbwoSmUnCOUeezXITPu5c6ImeNmmeKIDmoSqVuETS/jREvc6m4OvzBPHfWtcJ+myU6+avGXgMDOuq9+M+zj/5YjquUZ610qI3h8QARMXCccqAfaTzK1KMz2iU/mJ/08hxQc1Vx2avpC+Z9DZY9jUXL3Q/O0RTdYechWYrXUnPzBTQOC7vpLUyG7fscEOleub+Aw1XSO5qrOkw/dRX37dt3Cj5djIKzP9zPvJcG+XQ16nfiwk2yhUWYjZ7VaUS8ngADzgsGC9wi/4mltN3D1OKKbuhdApfby73vVJrCWnI42WESUsQqq80OV9ZFzt3fk5GVk3wa4NmmfF6+GDcuSTb48Ks93Dd2YtbxLU+UTnVTWfL7I0P8krUPgEv8IaMA7NOlp8d+TVASPqnXgK6Q+akwwnrmHhJMxtiG9gtBUBomMeyvtwilZ3CkbhUN/TPMwRZ6VkCL+JrjesGYGyhZgAjYZm5G0129sih3xehBcUsrr+SdWZwpNd9TNJHthVDbjM4g9DLPA26stPZUI8JcdK9M3TxbRHGPAk/6t+TFvo/kQmD4Lvtd3PVaUV4i89V40DzerJA2PNRD/V/dwARuItBaVNdYM83pp7YQVvcm/dtP+LY45nEh5/HU=
    on_success: change
    on_failure: change
    on_start: never
    on_pull_requests: false
